version: '2.29.2'
services:
  e-commerce-app:
    build: 
      context: .
      target: development
    container_name: e-commerce-app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
      - ./DB:/app/DB:ro
      - ./index.js:/app/index.js:ro
      - ./initiate-app.js:/app/initiate-app.js:ro
      - ./router-handler.js:/app/router-handler.js:ro
    env_file:
      - ./.env
  mongo-db:
    image: mongo
    restart: always